const imgUrl = process.env.REACT_APP_imgUrl;
const apiUrl = process.env.REACT_APP_apiUrl;
const apiGatewayUrl = process.env.REACT_APP_apiGatewayUrl;
const cloudinary_url = process.env.REACT_APP_cloudinary_url;
const cloudinary_name = process.env.REACT_APP_cloudinary_name;
const serverUrl = process.env.REACT_APP_serverUrl;
const APP_ENV = process.env.REACT_APP_APP_ENV;
const INTERCOM_APP_ID = process.env.REACT_APP_INTERCOM_APP_ID;
const GOOGLE_TRACKING_ID = process.env.REACT_APP_GOOGLE_TRACKING_ID;
const GOOGLE_EVENTS_TRACKING_ID = process.env.REACT_APP_GOOGLE_EVENTS_TRACKING_ID;
const DISPLAY_PAGE_INTERVAL = process.env.REACT_APP_DISPLAY_PAGE_INTERVAL;
const MAIN_PAGE_INTERVAL = process.env.REACT_APP_MAIN_PAGE_INTERVAL;
const HOST_PAGE_INTERVAL = process.env.REACT_APP_HOST_PAGE_INTERVAL;
const PERFORMANCE_PAGE_INTERVAL = process.env.REACT_APP_PERFORMANCE_PAGE_INTERVAL;
const FACEBOOK_APP_ID = process.env.REACT_APP_FACEBOOK_APP_ID;
const FACEBOOK_API_VERSION = process.env.REACT_APP_FACEBOOK_API_VERSION;
const GOOGLE_APP_ID = process.env.REACT_APP_GOOGLE_APP_ID;
const LINKEDIN_APP_ID = process.env.REACT_APP_LINKEDIN_APP_ID;
const APPLE_APP_ID = process.env.REACT_APP_APPLE_APP_ID;
const CAPTERRA_VID = process.env.REACT_APP_CAPTERRA_VID;
const CAPTERRA_VKEY = process.env.REACT_APP_CAPTERRA_VKEY;
const SQUARE_APPID = process.env.REACT_APP_SQUARE_APPID;
const SQUARE_LOCATION_ID = process.env.REACT_APP_SQUARE_LOCATION_ID;
const SEATSIO_SECREAT_KEY = process.env.REACT_APP_SEATSIO_SECREAT_KEY;
const SEATSIO_PUBLIC_KEY = process.env.REACT_APP_SEATSIO_PUBLIC_KEY;
const SEATSIO_DESIGNER_KEY = process.env.REACT_APP_SEATSIO_DESIGNER_KEY;
const AWS_APP_SYNC_URL = process.env.REACT_APP_AWS_APP_SYNC_URL;
const AWS_APP_SYNC_API_KEY = process.env.REACT_APP_AWS_APP_SYNC_API_KEY;
const AWS_APP_SYNC_REGION = process.env.REACT_APP_AWS_APP_SYNC_REGION;
const HOST_FACEBOOK_PIXEL_ID = process.env.REACT_APP_HOST_FACEBOOK_PIXEL_ID;
const DISPLAY_FACEBOOK_PIXEL_ID = process.env.REACT_APP_DISPLAY_FACEBOOK_PIXEL_ID;
const IP_GEO_LOCATION_API_KEY = process.env.REACT_APP_IP_GEO_LOCATION_API_KEY;
const TWILIO_KEY = process.env.REACT_APP_TWILIO_KEY;
const FROALA_KEY_3 = process.env.REACT_APP_FROALA_KEY_3;
const GETSTREAM_APP_KEY = process.env.REACT_APP_GETSTREAM_APP_KEY;
const GETSTREAM_SUPERADMIN_TOKEN = process.env.REACT_APP_GETSTREAM_SUPERADMIN_TOKEN;
const GETSTREAM_APP_ID = process.env.REACT_APP_GETSTREAM_APP_ID;
const MUX_SECRETKEY = process.env.REACT_APP_MUX_SECRETKEY;
const MUX_API_TOKEN = process.env.REACT_APP_MUX_API_TOKEN;
const MUX_ENV_KEY = process.env.REACT_APP_MUX_ENV_KEY;
const VOXEET_CONSUMER_SECRET = process.env.REACT_APP_VOXEET_CONSUMER_SECRET;
const VOXEET_CONSUMER_KEY = process.env.REACT_APP_VOXEET_CONSUMER_KEY;
const NETWORKING_WEBSOKET_URL = process.env.REACT_APP_NETWORKING_WEBSOKET_URL;
const AWS_PROJECT_REGION = process.env.REACT_APP_AWS_PROJECT_REGION;
const AWS_COGNITO_IDENTITY_POOL_ID = process.env.REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID;
const ZOOM_API_KEY = process.env.REACT_APP_ZOOM_API_KEY;
const AWS_APP_SYNC_URL_POLLS = process.env.REACT_APP_AWS_APP_SYNC_URL_POLLS;
const AWS_APP_SYNC_API_KEY_POLLS = process.env.REACT_APP_AWS_APP_SYNC_API_KEY_POLLS;
const AWS_APP_SYNC_URL_QA = process.env.REACT_APP_AWS_APP_SYNC_URL_QA;
const AWS_APP_SYNC_API_KEY_QA = process.env.REACT_APP_AWS_APP_SYNC_API_KEY_QA;
const AWS_KINESIS_DATA_STREAM_NAME = process.env.REACT_APP_AWS_KINESIS_DATA_STREAM_NAME;
const AWS_KINESIS_FIREHOSE_NAME = process.env.REACT_APP_AWS_KINESIS_FIREHOSE_NAME;
const AWS_KINESIS_VIDEO_ANALYTICS_STREAM_NAME = process.env.REACT_APP_AWS_KINESIS_VIDEO_ANALYTICS_STREAM_NAME;
const AWS_KINESIS_DYNAMO_DB_STREAM = process.env.REACT_APP_AWS_KINESIS_DYNAMO_DB_STREAM;
const VIDEO_PROGRESS_INTERVAL_CALL = process.env.REACT_APP_VIDEO_PROGRESS_INTERVAL_CALL;
const BACKSTAGE_CHANNEL_START_FROM = process.env.REACT_APP_BACKSTAGE_CHANNEL_START_FROM;
const WHITE_LABLE_DOMAIN_SETTING_API_URL = process.env.REACT_APP_WHITE_LABLE_DOMAIN_SETTING_API_URL;
const AWS_CLOUDWATCH_ACCESS_KEY = process.env.REACT_APP_AWS_CLOUDWATCH_ACCESS_KEY;
const AWS_CLOUDWATCH_ACCESS_ID = process.env.REACT_APP_AWS_CLOUDWATCH_ACCESS_ID;
const AWS_CLOUDWATCH_REGION = process.env.REACT_APP_AWS_CLOUDWATCH_REGION;
const HUBSPOT_TRACKING_ID = process.env.REACT_APP_HUBSPOT_TRACKING_ID;
const AWS_KINESIS_VIDEO_VIEWS_STREAM_NAME = process.env.REACT_APP_AWS_KINESIS_VIDEO_VIEWS_STREAM_NAME;
const RECORDING_VIEWS_START_DATE = process.env.REACT_APP_RECORDING_VIEWS_START_DATE;
const API_VERSION = process.env.REACT_APP_API_VERSION;
const CHARGEBEE_SITE = process.env.REACT_APP_CHARGEBEE_SITE;
const CHARGEBEE_API_KEY = process.env.REACT_APP_CHARGEBEE_API_KEY;
const AWS_APP_SESSION_LOG_URL = process.env.REACT_APP_AWS_APP_SESSION_LOG_URL;
const AWS_APP_SESSION_LOG_API_KEY = process.env.REACT_APP_AWS_APP_SESSION_LOG_API_KEY;
const AGORA_APP_ID = process.env.REACT_APP_AGORA_APP_ID;
const VONAGE_API_KEY = process.env.REACT_APP_VONAGE_API_KEY;
const AWS_APP_PUSH_NOTIFICATION_API_KEY = process.env.REACT_APP_AWS_APP_PUSH_NOTIFICATION_API_KEY;
const AWS_APP_PUSH_NOTIFICATION_API_URL = process.env.REACT_APP_AWS_APP_PUSH_NOTIFICATION_API_URL;
const AWS_APP_EXPO_PUSH_NOTIFICATION_API_URL = process.env.REACT_APP_AWS_APP_EXPO_PUSH_NOTIFICATION_API_URL;
const AWS_APP_EXPO_PUSH_NOTIFICATION_API_KEY = process.env.REACT_APP_AWS_APP_EXPO_PUSH_NOTIFICATION_API_KEY;
const ACCELEVENTS_DEFAULT_EVENT_ICON = process.env.REACT_APP_ACCELEVENTS_DEFAULT_EVENT_ICON;
const TOP_LOGO_IMAGE_BLACK = process.env.REACT_APP_TOP_LOGO_IMAGE_BLACK;
const TOP_LOGO_IMAGE_WHITE = process.env.REACT_APP_TOP_LOGO_IMAGE_WHITE;
const HEADER_LOGO_IMAGE = process.env.REACT_APP_HEADER_LOGO_IMAGE;
const WHITE_LOGO_IMAGE = process.env.REACT_APP_WHITE_LOGO_IMAGE;
const ACCELEVENTS_ICON_WHITE = process.env.REACT_APP_ACCELEVENTS_ICON_WHITE;
const SENTRY_ENV = process.env.REACT_APP_SENTRY_ENV;
const AWS_KINESIS_EXPO_VISIT_COUNT = process.env.REACT_APP_AWS_KINESIS_EXPO_VISIT_COUNT;
const BEEFREE_CLIENT_ID = process.env.REACT_APP_BEEFREE_CLIENT_ID;
const BEEFREE_CLIENT_SECRET = process.env.REACT_APP_BEEFREE_CLIENT_SECRET;
const ACCELEVENTS_LOGO_SQUARE = process.env.REACT_APP_ACCELEVENTS_LOGO_SQUARE;
const EXPO_VISIT_COUNT_WEBSOKET_URL = process.env.REACT_APP_EXPO_VISIT_COUNT_WEBSOKET_URL;
const AWS_KINESIS_VIDEO_ANALYTICS_STREAM = process.env.REACT_APP_VIDEO_ANALYTICS;
const AWS_KINESIS_MEETING_ANALYTICS_STREAM = process.env.REACT_APP_MEETING_ANALYTICS_STREAM;
const AWS_APP_EVENT_LIVE_STREAM_API_URL = process.env.REACT_APP_AWS_APP_EVENT_LIVE_STREAM_API_URL;
const AWS_APP_EVENT_LIVE_STREAM_API_KEY = process.env.REACT_APP_AWS_APP_EVENT_LIVE_STREAM_API_KEY;
const HOTJARID = process.env.REACT_APP_HOTJARID;
const REACT_APP_LINKEDIN_CLIENT_SECRET = process.env.REACT_APP_LINKEDIN_CLIENT_SECRET;
const GOOGLE_MAP_KEY = process.env.REACT_APP_GOOGLE_MAP_KEY;
const PAYPAL_CLIENT_ID = process.env.REACT_APP_PAYPAL_CLIENT_ID;
const RE_CAPTCHA_SITEKEY = process.env.REACT_APP_RE_CAPTCHA_SITEKEY;
const GOOGLE_FONTS_API_KEY = process.env.REACT_APP_GOOGLE_FONTS_API_KEY;
const AWS_APP_CHIME_RECORDING_ASSET_API_URL = process.env.REACT_APP_AWS_APP_CHIME_RECORDING_ASSET_API_URL;
const AWS_APP_CHIME_RECORDING_ASSET_API_KEY = process.env.REACT_APP_AWS_APP_CHIME_RECORDING_ASSET_API_KEY;
const AWS_APP_CMD_NOTIFICATION_API_URL = process.env.REACT_APP_AWS_APP_CMD_NOTIFICATION_API_URL;
const AWS_APP_CMD_NOTIFICATION_API_KEY = process.env.REACT_APP_AWS_APP_CMD_NOTIFICATION_API_KEY;
const PAYPAL_PILOT_PAYFLOW_LINK = process.env.REACT_APP_PAYPAL_PILOT_PAYFLOW_LINK;
const UNLAYER_PROJECT_ID = process.env.REACT_APP_UNLAYER_PROJECT_ID;
const UNLAYER_EMAIL_TEMPLATE_ID = process.env.REACT_APP_UNLAYER_EMAIL_TEMPLATE_ID;
const HUBSPOT_FORM_ID = process.env.REACT_APP_HUBSPOT_FORM_ID;
export {
  imgUrl,
  apiUrl,
  apiGatewayUrl,
  cloudinary_url,
  cloudinary_name,
  serverUrl,
  APP_ENV,
  INTERCOM_APP_ID,
  GOOGLE_TRACKING_ID,
  GOOGLE_EVENTS_TRACKING_ID,
  DISPLAY_PAGE_INTERVAL,
  MAIN_PAGE_INTERVAL,
  HOST_PAGE_INTERVAL,
  PERFORMANCE_PAGE_INTERVAL,
  FACEBOOK_APP_ID,
  FACEBOOK_API_VERSION,
  CAPTERRA_VID,
  CAPTERRA_VKEY,
  SQUARE_APPID,
  SQUARE_LOCATION_ID,
  SEATSIO_SECREAT_KEY,
  SEATSIO_PUBLIC_KEY,
  SEATSIO_DESIGNER_KEY,
  AWS_APP_SYNC_URL,
  AWS_APP_SYNC_API_KEY,
  AWS_APP_SYNC_REGION,
  HOST_FACEBOOK_PIXEL_ID,
  DISPLAY_FACEBOOK_PIXEL_ID,
  IP_GEO_LOCATION_API_KEY,
  TWILIO_KEY,
  FROALA_KEY_3,
  GETSTREAM_APP_KEY,
  GETSTREAM_SUPERADMIN_TOKEN,
  GETSTREAM_APP_ID,
  MUX_SECRETKEY,
  MUX_API_TOKEN,
  MUX_ENV_KEY,
  VOXEET_CONSUMER_SECRET,
  VOXEET_CONSUMER_KEY,
  NETWORKING_WEBSOKET_URL,
  AWS_PROJECT_REGION,
  AWS_COGNITO_IDENTITY_POOL_ID,
  ZOOM_API_KEY,
  AWS_APP_SYNC_URL_POLLS,
  AWS_APP_SYNC_API_KEY_POLLS,
  AWS_APP_SYNC_URL_QA,
  AWS_APP_SYNC_API_KEY_QA,
  AWS_KINESIS_DATA_STREAM_NAME,
  AWS_KINESIS_FIREHOSE_NAME,
  AWS_KINESIS_VIDEO_ANALYTICS_STREAM_NAME,
  AWS_KINESIS_DYNAMO_DB_STREAM,
  VIDEO_PROGRESS_INTERVAL_CALL,
  WHITE_LABLE_DOMAIN_SETTING_API_URL,
  BACKSTAGE_CHANNEL_START_FROM,
  AWS_CLOUDWATCH_ACCESS_ID,
  AWS_CLOUDWATCH_ACCESS_KEY,
  AWS_CLOUDWATCH_REGION,
  HUBSPOT_TRACKING_ID,
  AWS_KINESIS_VIDEO_VIEWS_STREAM_NAME,
  RECORDING_VIEWS_START_DATE,
  API_VERSION,
  CHARGEBEE_SITE,
  CHARGEBEE_API_KEY,
  AWS_APP_SESSION_LOG_URL,
  AWS_APP_SESSION_LOG_API_KEY,
  AGORA_APP_ID,
  VONAGE_API_KEY,
  AWS_APP_PUSH_NOTIFICATION_API_KEY,
  AWS_APP_PUSH_NOTIFICATION_API_URL,
  AWS_APP_EXPO_PUSH_NOTIFICATION_API_URL,
  AWS_APP_EXPO_PUSH_NOTIFICATION_API_KEY,
  SENTRY_ENV,
  ACCELEVENTS_DEFAULT_EVENT_ICON,
  TOP_LOGO_IMAGE_BLACK,
  TOP_LOGO_IMAGE_WHITE,
  HEADER_LOGO_IMAGE,
  WHITE_LOGO_IMAGE,
  ACCELEVENTS_ICON_WHITE,
  HOTJARID,
  AWS_KINESIS_EXPO_VISIT_COUNT,
  BEEFREE_CLIENT_ID,
  BEEFREE_CLIENT_SECRET,
  ACCELEVENTS_LOGO_SQUARE,
  EXPO_VISIT_COUNT_WEBSOKET_URL,
  AWS_KINESIS_VIDEO_ANALYTICS_STREAM,
  AWS_KINESIS_MEETING_ANALYTICS_STREAM,
  AWS_APP_EVENT_LIVE_STREAM_API_URL,
  AWS_APP_EVENT_LIVE_STREAM_API_KEY,
  GOOGLE_APP_ID,
  LINKEDIN_APP_ID,
  REACT_APP_LINKEDIN_CLIENT_SECRET,
  APPLE_APP_ID,
  GOOGLE_MAP_KEY,
  PAYPAL_CLIENT_ID,
  RE_CAPTCHA_SITEKEY,
  GOOGLE_FONTS_API_KEY,
  AWS_APP_CHIME_RECORDING_ASSET_API_URL,
  AWS_APP_CHIME_RECORDING_ASSET_API_KEY,
  AWS_APP_CMD_NOTIFICATION_API_URL,
  AWS_APP_CMD_NOTIFICATION_API_KEY,
  PAYPAL_PILOT_PAYFLOW_LINK,
  UNLAYER_PROJECT_ID,
  UNLAYER_EMAIL_TEMPLATE_ID,
  HUBSPOT_FORM_ID,
};
