import React from 'react';
import LoginLayout from '../../components/Layout/LoginLayout/LoginLayout';
import AdminWLLayout from '../../components/Layout/AdminWLLayout/AdminLayout';
import NewAdminLayoutWL from '../../components/Layout/AdminWLLayout/NewAdminLayoutWL';

const showFeedBack = false;
const Login = React.lazy(() => import('./Login'));
const NewLogin = React.lazy(() => import('./NewLogin'));
const EventsList = React.lazy(() => import('../admin/event/index'));
const OrganizationList = React.lazy(() => import('../admin/organizations/index'));
const WhiteLabelList = React.lazy(() => import('../admin/whiteLabelList/index'));
const WhiteLabelUserManagement = React.lazy(() => import('../admin/event/WhiteLabelUserManagement'));
const OrganizationSettings = React.lazy(() => import('../admin/event/organizationSettings'));
const WLEnterpriseDashboard = React.lazy(() => import('../admin/event/WLEnterpriseDashboard'));
// const WhiteLabelEventList = React.lazy(() => import('../admin/event/whiteLabelEvent'));
const EditEvent = React.lazy(() => import('../admin/event/editEvent'));
const Analytics = React.lazy(() => import('../admin/analytics/index'));
const EventBilling = React.lazy(() => import('../admin/event/EventBilling'));
const EventChargeDetails = React.lazy(() => import('../admin/event/EventChargeDetails/EventChargeDetails'));
const SessionLogs = React.lazy(() => import('../admin/event/SessionLogs'));
const Integrations = React.lazy(() => import('../admin/Integrations'));
const FeeAdjustment = React.lazy(() => import('../../components/FeeAdjust/FeeAdjust'));
const WLSettings = React.lazy(() => import('../admin/whiteLabelList/WLSettings'));
const EmailTemplateBuilder = React.lazy(() => import('../../components/Beefree/EmailTemplateBuilder'));
const EmailTemplates = React.lazy(() => import('../../components/Beefree/EmailTemplates'));
const WlMuxDomain = React.lazy(() => import('../admin/event/WlMuxDomain'));
const isProtected = true;

export default [
  {
    path: '/u/login',
    component: NewLogin,
    title: 'Sign in',
    exact: true,
    strict: true,
    layoutProps: { loginType: 'generalLogin' },
  },
  {
    path: '/u/superadmin/login',
    component: Login,
    title: 'Events',
    exact: true,
    wrapperLayout: LoginLayout,
    layoutProps: { loginType: 'superadmin', showFeedBack },
  },
  {
    path: '/u/wl-login/:params',
    component: Login,
    title: 'Sign in',
    exact: true,
    wrapperLayout: LoginLayout,
    layoutProps: { loginType: 'whiteLabel', showFeedBack },
  },
  {
    path: '/u/superadmin/events',
    component: EventsList,
    title: 'Events',
    isAdmin: true,
    isProtected,
    exact: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/organizations',
    component: OrganizationList,
    title: 'Organizations',
    isAdmin: true,
    isProtected,
    exact: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/whiteLabel',
    component: WhiteLabelList,
    title: 'whiteLabel',
    isAdmin: true,
    isProtected,
    exact: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, isEnterprise: true },
  },
  {
    path: '/u/superadmin/wl-mux-domain',
    component: WlMuxDomain,
    title: 'whiteLabel mux domain',
    isAdmin: true,
    isProtected,
    exact: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, isEnterprise: true },
  },
  {
    path: '/u/superadmin/edit-email-templates',
    component: EmailTemplates,
    title: 'Edit Email templates',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
    footerTemplate: 'footer-custom-template',
  },
  {
    path: '/u/superadmin/edit-email-templates/waitlist',
    component: EmailTemplateBuilder,
    title: 'Waitlist Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'WAIT_LIST_RELEASE',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/attendee-checkin',
    component: EmailTemplateBuilder,
    title: 'Attendee Check-in Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'ATTENDEE_CHECKIN',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/magic-link',
    component: EmailTemplateBuilder,
    title: 'Magic Link Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'MAGIC_LINK_CODE',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },

  {
    path: '/u/superadmin/edit-email-templates/reset-password',
    component: EmailTemplateBuilder,
    title: 'Reset Password Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'RESET_PASSWORD',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },

  {
    path: '/u/superadmin/edit-email-templates/organizer-access',
    component: EmailTemplateBuilder,
    title: 'Organizer Access Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'ORGANIZER_TEAM_ACCESS',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },

  {
    path: '/u/superadmin/edit-email-templates/staff-access',
    component: EmailTemplateBuilder,
    title: 'Staff Access Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'STAFF_ACCESS',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },

  {
    path: '/u/superadmin/edit-email-templates/request-notification',
    component: EmailTemplateBuilder,
    title: 'Request Notification Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'REQUEST_NOTIFICATION',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/participant-question',
    component: EmailTemplateBuilder,
    title: 'Participant Question Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'PARTICIPANT_QUESTION',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/support-question',
    component: EmailTemplateBuilder,
    title: 'Support Question Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'SUPPORT_QUESTION',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/cart-abendonment',
    component: EmailTemplateBuilder,
    title: 'Cart Abendonment Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'CART_ABANDONMENT',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/meeting-notification',
    component: EmailTemplateBuilder,
    title: 'Meeting Notification Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'MEETING_NOTIFICATION',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/buyer-receipt-auction',
    component: EmailTemplateBuilder,
    title: 'Buyer Recepit Auction Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'BUYER_RECEIPT_AUCTION',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/event-ticket-refund',
    component: EmailTemplateBuilder,
    title: 'Event Ticket Refund Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'EVENT_TICKET_REFUND',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/edit-email-templates/admin-order-confirmation-email',
    component: EmailTemplateBuilder,
    title: 'Admin Order Confirmation Email template',
    exact: true,
    isProtected,
    isAdmin: true,
    emailType: 'ADMIN_ORDER_CONFIRMATION_EMAIL',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/superadmin/billing',
    component: EventBilling,
    title: 'Events Billing',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/wl/:params/users',
    component: WhiteLabelUserManagement,
    title: 'WhiteLabel User Management',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/wl/:whiteLabelUrl/analytics',
    component: Analytics,
    title: 'Analytics page',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/wl/:whiteLabelUrl/integrations',
    component: Integrations,
    title: 'Integrtions page',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/sales/:params/analytics',
    component: Analytics,
    title: 'Analytics page',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/wl/:params/settings',
    component: OrganizationSettings,
    title: 'Organization Settings',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/wl/:params/feeadjustment',
    component: FeeAdjustment,
    title: 'WhiteLabel Fee Adjustment',
    exact: true,
    isProtected,
    isAdmin: true,
    isFrom: 'WhiteLabel',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/superadmin/whiteLabel/:params',
    component: WLSettings,
    title: 'White Label Settings',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/o/:params/feeadjustment',
    component: FeeAdjustment,
    title: 'Organizer Fee Adjustment',
    exact: true,
    isProtected,
    isAdmin: true,
    isFrom: 'Organizer',
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/superadmin/edit/:eventId',
    component: EditEvent,
    title: 'Edit Event',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
  {
    path: '/u/superadmin/log/:params',
    component: SessionLogs,
    title: 'Session Logs',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true },
  },
  {
    path: '/u/wl/:params/home',
    component: WLEnterpriseDashboard,
    title: 'Events',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: NewAdminLayoutWL,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },

  {
    path: '/u/superadmin/billing/:params',
    component: EventChargeDetails,
    title: 'Event Charge Details',
    exact: true,
    isProtected,
    isAdmin: true,
    wrapperLayout: AdminWLLayout,
    layoutProps: { isAdmin: true, whiteLabelType: true },
  },
];
